language: python
python:
  - "3.6"

before_install:
  - sudo apt-get -qq update

install:
  - apt-get install -y nodejs npm
  - pip install pipenv
  - pipenv install

script:
  - make html
  - cp README.md html/

branches:
  only:
    - master

deploy:
  provider: pages
  edge: true # use latest dpl release
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: html
  on:
    branch: master
